export { EndPointMapper } from './end-point.mapper';
export { FunctionMapper } from './function.mapper';
export { GenericNomenclatorMapper } from './generic-nomenclator.mapper';
export { MenuMapper } from './menu.mapper';
export { MunicipalityMapper } from './municipality.mapper';
export { ProvinceMapper } from './province.mapper';
export { RolMapper } from './rol.mapper';
export { TrazaMapper } from './traza.mapper';
export { UserMapper } from './user.mapper';
