import {
  BusinessRepository,
  ClientRepository,
  EndPointRepository,
  FunctionRepository,
  GenericNomenclatorRepository,
  MenuRepository,
  MunicipalityRepository,
  PlanRepository, ProductRepository,
  ProvinceRepository,
  RolRepository,
  LogHistoryRepository,
  UserRepository,
} from './repository';

export const repository = [
  LogHistoryRepository,
  UserRepository,
  RolRepository,
  FunctionRepository,
  EndPointRepository,
  MenuRepository,
  GenericNomenclatorRepository,
  MunicipalityRepository,
  ProvinceRepository,
  BusinessRepository,
  ClientRepository,
  PlanRepository,
  ProductRepository,
];
